pub fn lookup(name: &str) -> Option<Builtin> {
    match name {
        "abs" => Some(Builtin::Abs),
        "acos" => Some(Builtin::Acos),
        "asin" => Some(Builtin::Asin),
        "atan" => Some(Builtin::Atan),
        "atan2" => Some(Builtin::Atan2),
        "ceil" => Some(Builtin::Ceil),
        "cos" => Some(Builtin::Cos),
        "cosh" => Some(Builtin::Cosh),
        "e" => Some(Builtin::E),
        "exp" => Some(Builtin::Exp),
        "fac" => Some(Builtin::Fac),
        "floor" => Some(Builtin::Floor),
        "ln" => Some(Builtin::Ln),
        "log" => Some(Builtin::Log),
        "log10" => Some(Builtin::Log10),
        "ncr" => Some(Builtin::Ncr),
        "npr" => Some(Builtin::Npr),
        "pi" => Some(Builtin::Pi),
        "pow" => Some(Builtin::Pow),
        "sin" => Some(Builtin::Sin),
        "sinh" => Some(Builtin::Sinh),
        "sqrt" => Some(Builtin::Sqrt),
        "tan" => Some(Builtin::Tan),
        "tanh" => Some(Builtin::Tanh),
        _ => None,
    }
}
pub fn arity(function: Builtin) -> usize {
    match function {
        Builtin::Abs => 1,
        Builtin::Acos => 1,
        Builtin::Asin => 1,
        Builtin::Atan => 1,
        Builtin::Atan2 => 2,
        Builtin::Ceil => 1,
        Builtin::Cos => 1,
        Builtin::Cosh => 1,
        Builtin::E => 0,
        Builtin::Exp => 1,
        Builtin::Fac => 1,
        Builtin::Floor => 1,
        Builtin::Ln => 1,
        Builtin::Log => 1,
        Builtin::Log10 => 1,
        Builtin::Ncr => 2,
        Builtin::Npr => 2,
        Builtin::Pi => 0,
        Builtin::Pow => 2,
        Builtin::Sin => 1,
        Builtin::Sinh => 1,
        Builtin::Sqrt => 1,
        Builtin::Tan => 1,
        Builtin::Tanh => 1,
    }
}